### ISSUE TITLE
Matrix client support

### ISSUE THREAD

**Issue by du64** [spacebarchat/spacebarchat#177]
It would be awesome to use Fosscord as an exact clone of the Discord client, but make it matrix compatible.

I don't actually use Discord, and all of my people are on Matrix, but I really like the client (minus the Nitro stuff and new home feed thing) so I'd like to use Fosscord as a Matrix client.

Thoughts?

**Comment by FSG-Cat** [comment]
What you are actually looking for is almost guaranteed to be more like the cinny matrix client. Because making a discord client be a matrix client is not exactly easy unless your literally doing it via advanced bridge and even then you need a matrix event handling engine or E2BE is your only option. Aka End to Bridge Encryption. And thats if you even support Encryption.

The made for fosscord client family wont be using UI that is within a Lawsuit filed by a first year and won at motion for summary judgement (Not a lawyer just watched way too much Law Youtube so this is possibily accurate) to be in trouble. 

Its just well a lot of stuff that has to be changed under the hood to get a matrix client as a discord one if the discord client isnt a multi system client. Multi system clients already have the architecture in their code to accept multiple message stacks since Fosscord and Matrix dont talk compatible schemas. 

Just to note this comment might have to be updated. Its written semi hastely.

**Comment by erkinalp** [comment]
see Flam3rboy/trant

**Comment by du64** [comment]
> What you are actually looking for is almost guaranteed to be more like the cinny matrix client. Because making a discord client be a matrix client is not exactly easy unless your literally doing it via advanced bridge and even then you need a matrix event handling engine or E2BE is your only option. Aka End to Bridge Encryption. And thats if you even support Encryption.
> 
> The made for fosscord client family wont be using UI that is within a Lawsuit filed by a first year and won at motion for summary judgement (Not a lawyer just watched way too much Law Youtube so this is possibily accurate) to be in trouble.
> 
> Its just well a lot of stuff that has to be changed under the hood to get a matrix client as a discord one if the discord client isnt a multi system client. Multi system clients already have the architecture in their code to accept multiple message stacks since Fosscord and Matrix dont talk compatible schemas.
> 
> Just to note this comment might have to be updated. Its written semi hastely.

So maybe I should just modify Cinny, because in its current state, it isn't exactly like Discord, and I want a 1-1 Matrix client
