### ISSUE TITLE
Soon Fooscord should be conform with Discord ToS?

### ISSUE THREAD

**Issue by TigerbyteDev** [spacebarchat/spacebarchat#178]
I've stumbled about Fosscord yesterday and sure, it's against Discord ToS. But in 2023/2024 it shouldn't be because of EU's Digital Market Act?

**Comment by TheGoldenSun** [comment]
May you explain what news are you going on about?

**Comment by TigerbyteDev** [comment]
It's a new EU Law
https://ec.europa.eu/info/strategy/priorities-2019-2024/europe-fit-digital-age/digital-markets-act-ensuring-fair-and-open-digital-markets_en

**Comment by greysilly7** [comment]
Fosscord is not a company nor is it based in the EU so why does this matter?

**Comment by greysilly7** [comment]
Also fosscord isn't against Discord TOS since it doesn't really interact with discord...

**Comment by FSG-Cat** [comment]
Whenever we get around to making an official Fosscord client with backwards compatibility mode that client might be legal when the DMA kicks in on Discord is an argument that could be made. But ye like these constant issues about Fosscord and its TOS status are starting to become silly. 

Fosscord has not yet gotten a C&D from Discord Inc so they clearly have not yet deicided that the project is enough of a problem to warrant attempting to take actions to stop it. So clearly fosscord is not against the TOS because it does not interact at all with discord in that way. Once the official client is a thing it will be 100% against the TOS until the TOS is updated. Yes yes we know that the TOS is just CYA for the Anti spam but still.

**Comment by TigerbyteDev** [comment]
But in a FAQ you said it is?

**Comment by FSG-Cat** [comment]
> But in a FAQ you said it is?

Please link me to the specific FAQ your refering to because i am not aware of this FAQ

**Comment by TigerbyteDev** [comment]
> > But in a FAQ you said it is?
> 
> Please link me to the specific FAQ your refering to because i am not aware of this FAQ

I lost the link, had found it when searching a bit ¯\_(ツ)_/¯
